module.exports = {
  BUS_SEARCH_PENDING: "BUS_SEARCH_PENDING",
  BUS_OPTION_SELECTION: "BUS_OPTION_SELECTION",
  SEAT_LAYOUT_PENDING: "SEAT_LAYOUT_PENDING",
  SEAT_SELECTION: "SEAT_SELECTION",
  SEAT_CONFIRMATION: "SEAT_CONFIRMATION",
  PRICE_CONFIRMATION: "PRICE_CONFIRMATION",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
};
