module.exports = {
  BUS_SEARCH_PENDING: "BUS_SEARCH_PENDING",
  BUS_OPTION_SELECTION: "BUS_OPTION_SELECTION",

  SEAT_LAYOUT_PENDING: "SEAT_LAYOUT_PENDING",
  SEAT_SELECTION: "SEAT_SELECTION",
  SEAT_CONFIRMATION: "SEAT_CONFIRMATION",

  FINAL_CONFIRMATION: "FINAL_CONFIRMATION",
  AWAITING_PRICE: "AWAITING_PRICE",
  FARE_SENT: "FARE_SENT",

  PAYMENT_PENDING: "PAYMENT_PENDING",
  AWAITING_MANUAL_VERIFICATION: "AWAITING_MANUAL_VERIFICATION",

  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
};