const BOOKING_STATUS = {
  DRAFT: "DRAFT",
  PROCESSING: "PROCESSING",
  AVAILABILITY_SHARED: "AVAILABILITY_SHARED",
  CONFIRMED_BY_USER: "CONFIRMED_BY_USER",
  AWAITING_FARE: "AWAITING_FARE",
  FARE_SENT: "FARE_SENT",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

module.exports = BOOKING_STATUS;