const TRAIN_MANUAL_STATES = {
  INIT: "TRAIN_MANUAL_INIT",

  // Admin checking availability
  AWAITING_AVAILABILITY: "TRAIN_MANUAL_AWAITING_AVAILABILITY",

  // After admin sends AVAILABLE / WAITING LIST / RAC
  WAITING_USER_DECISION: "TRAIN_MANUAL_WAITING_USER_DECISION",

  // User pressed proceed
  USER_CONFIRMED: "TRAIN_MANUAL_USER_CONFIRMED",

  // Admin sent fare
  FARE_SENT: "TRAIN_MANUAL_FARE_SENT",

  // Waiting for payment
  PAYMENT_PENDING: "TRAIN_MANUAL_PAYMENT_PENDING",

  // Payment done
  PAYMENT_SUCCESS: "TRAIN_MANUAL_PAYMENT_SUCCESS",

  // Booking completed
  CONFIRMED: "TRAIN_MANUAL_CONFIRMED",

  // Cancelled by user
  CANCELLED: "TRAIN_MANUAL_CANCELLED",

  // Very low confirmation case
  NO_CHANCE: "TRAIN_MANUAL_NO_CHANCE",
};

module.exports = TRAIN_MANUAL_STATES;