const TRAIN_MANUAL_STATES = {
  INIT: "TRAIN_MANUAL_INIT",
  AVAILABILITY_SENT: "TRAIN_MANUAL_AVAILABILITY_SENT",
  WAITING_CONFIRMATION: "TRAIN_MANUAL_WAITING_CONFIRMATION",
  CONFIRMED: "TRAIN_MANUAL_CONFIRMED",
  CANCELLED: "TRAIN_MANUAL_CANCELLED",
};

module.exports = TRAIN_MANUAL_STATES;
