const TRAIN_MANUAL_STATES = {
  INIT: "TRAIN_MANUAL_INIT",

  // Admin selected booking for processing
  PROCESSING: "TRAIN_MANUAL_PROCESSING",

  // After admin sends AVAILABLE / WAITING LIST / RAC
  AWAITING_CONFIRMATION: "TRAIN_MANUAL_AWAITING_CONFIRMATION",

  // User pressed confirm
  USER_CONFIRMED: "TRAIN_MANUAL_USER_CONFIRMED",

  // Admin triggered TICKET_PRICE
  AWAITING_FARE_INPUT: "TRAIN_MANUAL_AWAITING_FARE_INPUT",

  // Fare sent to user
  FARE_SENT: "TRAIN_MANUAL_FARE_SENT",

  // Waiting for payment
  PAYMENT_PENDING: "TRAIN_MANUAL_PAYMENT_PENDING",

  // Payment success
  PAYMENT_SUCCESS: "TRAIN_MANUAL_PAYMENT_SUCCESS",

  // Booking completed
  CONFIRMED: "TRAIN_MANUAL_CONFIRMED",

  // Cancelled by user
  CANCELLED: "TRAIN_MANUAL_CANCELLED",

  // No chance case
  NO_CHANCE: "TRAIN_MANUAL_NO_CHANCE",
};

module.exports = TRAIN_MANUAL_STATES;