module.exports = {
START: "TRAIN_QUICK_BOOK_START",
ENTRY_MODE: "TRAIN_QUICK_BOOK_ENTRY_MODE",
GROUP_WAITING: "TRAIN_QUICK_BOOK_GROUP_WAITING",
FROM: "TRAIN_QUICK_BOOK_FROM",
TO: "TRAIN_QUICK_BOOK_TO",
DATE: "TRAIN_QUICK_BOOK_DATE",
TRAIN: "TRAIN_QUICK_BOOK_TRAIN",
TIME: "TRAIN_QUICK_BOOK_TIME",
BERTH: "TRAIN_QUICK_BOOK_BERTH",
SUMMARY: "TRAIN_QUICK_BOOK_SUMMARY",
};
