module.exports = {
  START: "BUS_QUICK_BOOK_START",
  FROM: "BUS_QUICK_BOOK_FROM",
  TO: "BUS_QUICK_BOOK_TO",
  DATE: "BUS_QUICK_BOOK_DATE",
  OPERATOR: "BUS_QUICK_BOOK_OPERATOR",
  TIME: "BUS_QUICK_BOOK_TIME",
  SEAT: "BUS_QUICK_BOOK_SEAT",
};