module.exports = {
  START: "BUS_QUICK_BOOK_START",
  OPERATOR: "BUS_QUICK_BOOK_OPERATOR",
  DATE: "BUS_QUICK_BOOK_DATE",
  TIME: "BUS_QUICK_BOOK_TIME",
  SEAT: "BUS_QUICK_BOOK_SEAT",
  CONFIRM: "BUS_QUICK_BOOK_CONFIRM",
};