module.exports = {
  START: "BUS_QUICK_BOOK_START",
  ENTRY_MODE: "BUS_QUICK_BOOK_ENTRY_MODE",
  GROUP_WAITING: "BUS_QUICK_BOOK_GROUP_WAITING",
  FROM: "BUS_QUICK_BOOK_FROM",
  TO: "BUS_QUICK_BOOK_TO",
  DATE: "BUS_QUICK_BOOK_DATE",
  OPERATOR: "BUS_QUICK_BOOK_OPERATOR",
  TIME: "BUS_QUICK_BOOK_TIME",
  SEAT: "BUS_QUICK_BOOK_SEAT",
  SUMMARY: "BUS_QUICK_BOOK_SUMMARY",
};