module.exports = {
  PAYMENT_PENDING_APPROVAL: "PAYMENT_PENDING_APPROVAL",
  PAYMENT_AWAITING: "PAYMENT_AWAITING",
  PAYMENT_SUBMITTED: "PAYMENT_SUBMITTED",
  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
};
